name: setup for cd
description: setup of nodejs 18 and python 3.11 for search-ui

runs:
  using: composite
  steps:
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Verify Node.js installation
      shell: bash
      run: |
        node --version
        npm --version

    - name: Install npm
      shell: bash
      run: npm ci

    - name: Install Chrome
      shell: bash
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo tee /usr/share/keyrings/google-linux-keyring.gpg > /dev/null
        echo 'deb [signed-by=/usr/share/keyrings/google-linux-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version
