sudo: required
language: node_js
addons:
  chrome: stable
notifications:
  email:
    on_success: change
    on_failure: always
node_js:
- 8.15.1
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - npm install -g npm@5.5.1
  - if [ "x$TRAVIS_TAG" != "x" ]; then wget https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$VERACODE_WRAPPER_VERSION/vosp-api-wrappers-java-$VERACODE_WRAPPER_VERSION.jar ; fi
  - sudo apt-get install libgconf2-4
script:
- source read.version.sh
- echo $PACKAGE_JSON_VERSION
- yarn run injectTag
- yarn run build
- if [ "x$TRAVIS_TAG" != "x" ]; then yarn run minimize ; fi
- yarn run unitTests
- if [ "x$TRAVIS_TAG" != "x" ]; then yarn run accessibilityTests ; fi
- set +e
- yarn run uploadCoverage
- set -e
- yarn run validateTypeDefinitions
after_success:
- if [ "x$TRAVIS_TAG" != "x" ]; then bash ./deploy.doc.sh ; fi
- yarn run docsitemap
- yarn run zipForGitReleases
- yarn run zipForVeracode
- if [ "x$TRAVIS_TAG" != "x" ]; then java -jar vosp-api-wrappers-java-$VERACODE_WRAPPER_VERSION.jar -vid $VERACODE_KEY_ID  -vkey $VERACODE_SECRET -action uploadandscan -appname Coveo -sandboxname "JS UI" -createprofile true -filepath veracode.zip -version "Travis build [ $TRAVIS_JOB_NUMBER ] on branch [ $TRAVIS_BRANCH ]" ; else echo "Build was triggered from a fork; skipping Veracode" ; fi
env:
  global:
  - COMMIT_AUTHOR_EMAIL: sandbox_JSUI@coveo.com
deploy:
  - provider: npm
    email: sandbox_JSUI@coveo.com
    skip_cleanup: true
    api_key:
      secure: tEFBMHm1YjFLJa8lDs9tvE/YSZ7xItu1+zgSzEVUzVZngUWybsle5pMgGYzwq2HhoV3l6hw+tg9+aSKuxCkk0ezF5L9emHDBNUksB3vD7+hQ9ebIHlv/D3QI/Q6cxh358M6pF1sjw9NP7g2rIbYkIZtEPpz7DkWUDhsKAg0VFVMH4q2WJ6Lt8q2LW9acC87zR4FBHkB8pYOuQzW7tLNhsBOmRqU4qge6p3u0ox90N9UTDVGQVzwnD99zixCcJc0WhdnuK7wTf3EebMA+iBXD0/V4VlvNUBA/cVPWujZkvYw3gYO+JuwMuFqXAXQiAXuoyEaPbmCIdD+Lhj+Yj8HMspncl0vhcfrf1v8xdnqfgmf+TSEXLAMGdndUhlzIEHhPi39IUx7EKKdtayP0oYoEuWRjXF6EoAy+d5Y1NO/Q5tpncI7WaXXB+uaj+43fs4qS36hXRDdPGL8wHLPvvu0ndFoIipw9SPC+p2vj/VSj0HHrz/dBD4QF+zUM+IVuptZJ82bS7ozBpdX2nZVYsZka9XSuiQuMzs/P81dT6ksTSfbIvtwlH8lI17UbNN8dTXiFQ5Ij5sUCxag9heFnOicRV3q1eSNF3bYVrjlNnLx7rZsGqoln4TaTe6oX7+V3gXRuCofrh44kj5ZiwgiMR3LA8Xc7z2QrcegQYD04AvCStDY=
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "! $TRAVIS_TAG =~ .*beta.*"
  - provider: script
    script: node deploy.beta.js
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "$TRAVIS_TAG =~ .*beta.*"
  - provider: releases
    api_key:
      secure: jKNS2mWnLUP5kQkjApoIFxQVXAr8ed3nsTIltY6gOvf1/2kbkS0WbzR7Km9lewFA2ZEBSFAu/ek+ewXjEx8FVQAe3CeCS1sS5RVqU/2YvFGBPYzzVw1l3FOJkQsvruRc7UzkznXbLvk+7LerHDpsy3p6ut8stMokztiq8QyWN+GHhrB/QgBQV/swPx40QknAIXndtLEPQfttukLowAdH9ml2BgrgE0/3iitmja/8eIQxVT6dlFyXYV+iU44kPyS595wM7eakUGXNFB2W9sUZ9IY/8lUqPz85G3FkKyiPv3SZJRs158/32+vvdXAtT/wtHjP5PqESPv/pL31M9IpQYYIdTSPwUZtOdRZ6JrxV/xusQ2Nm5p3qNrKgtkEZ921BGHJEMK9xs0yAhMuT39JLhoZE30g8SXokWQWi6WzrRELODYubVMaXTmfgv2ZZN4T3B8xNSabmE3Jm7Gj5Lb9wdR+pbWxPlB475i4H7grOHAN9xRIWokAIIN9RuTPRx1XuxhLUI9BH/GrJXNZbv1800rqF15W9Yuw1RqMfrSWq2snyDalXW3gLHYeAFAP1hfD2mU1zySjP/HQ6VkCwmgCjlAg4W5xK4NlXX0C/EIkoLKhSefxLdhquMZQTION+v0fOvl7Kdz17vt231dEIjNZxsBlLL+JZoxOZA5tVRDMNbko=
    file_glob: true
    file:
    - search-ui.zip
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
  - provider: s3
    access_key_id: AKIAYKDJLZIT462WODCI
    secret_access_key:
      secure: sT8isIiaAIg/Ic7x8cCD3anwCEHAyzG/IWkngmkf5c128NEwUIUdmsQJ1hi4Bw84zk1OOb3id+yXjeaTuKDgIkxe/jk3e2xZ7xElfLNTOln6QLkgsYpKFtGHiKjROOHOb5+Es6L1mxpHWbXH9ebmEhRduUw/BeHWW2MfZmfb434DgvatViRm8DOeROeqlYnbCda5ZELuT5SdwEs/CbExaiSL0WKVoTvcxbe+At4uVnTuc6SYyOvRoblx/q6Ra6mdRipluMs7Go93eu/Oqo7cZ2akrNSi/WBXGqL/wXxe2pYsziSABWjQaqWXD/jKte1ZBx7OXssn88DUKat/RrL7Ak30WHzgY/goiNV+EPT/wtNYWHP3suAzzGqNNMhsPx0lSI7vSUga72J3hV1TOsX9ORosiRm1c2fnmNB9vJdH7yAX7lWpqH2XuOrldVvvTGazSJYx93eBukDViFCZ6egeb+gMT8VQ38uitwd9BZaMhycoujZgSjhx7JnbHUoUdXkdT3XBNV7fINTozWCNJW81iJN+JuLZzneJ/CbjmjkfGcVoFFPCD9rGSj8DbgvWpt8rkwI4ZfHTNOgO9iWgSklpk9r2wgM7Z87V2Zpu8UX/QCFxy8IREtJUo6X9YG9nBoy21wUa9zia2SWpideur9cXb6U0+q84onHVlA0Ehp/1OYs=
    bucket: coveo-nprod-binaries
    local-dir: bin
    upload-dir: proda/StaticCDN/searchui/v$PACKAGE_JSON_VERSION
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "! $TRAVIS_TAG =~ .*beta.*"

after_deploy:
- node invalidate.cloudfront.js
branches:
  only:
  - master
  - "/^.*release.*$/"
  - "/2\\.[0-9]+\\.[0-9]+/"
