sudo: false
language: node_js
notifications:
  email:
    on_success: change
    on_failure: always
node_js:
- 8.5.0
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- npm install -g npm@5.5.1
script:
- source read.version.sh
- echo $PACKAGE_JSON_VERSION
- yarn run injectTag
- yarn run build
env:
  global:
  - COMMIT_AUTHOR_EMAIL: sandbox_JSUI@coveo.com
deploy:
- provider: s3
  access_key_id: AKIAIMXKOBWDLZJPYWOQ
  secret_access_key:
    secure: Nh1K6QIXPaUFtKzA2D5f6LmW9Inf+fzZXQEKhFLAdNMITqxc9IPgryQEIrr/BqRlOdTgzod4kbHAu0tybhqvDQ7UtX6n+nLGjA4IbJ6Xtdn+yKBkzpy2zJUx2qqsuGFB2fOTJLC3QCX+eRvLdCt6uSjhhJAMNyDNo19UDRQEsVLqpHvj+0RI0yR9EmvMdAovaUViiVdkkjUmlZo9RWmJR83NyxFCEmmXKs5iqNiOEJpwjemdoEfR8oeRCvzosp1Wz2MzWIs/h+GuLcv/RGwKCkdkM4lBO2Rn/E2w4n0uz9Bn3n7QNvKgPzAqz1Us4a0ISu52TgnQvQ1tLvxhnkJeHMKI2mQ6UbICKWq0CG5Q+fotHU4I3mzws5AoXzFimiYXcbYzzduZHHTsTqNinmMfukPHwmfMQ7mUjcAWLhjaarz15Jr0amiwYAf7lFHjM+nMzgKW0hR9oq65A9MnR3nkJi8LCECTHJsps7AZWWSTrjkbTURGy6KlnACQZT79+yUBaEg+egIO3x5LWev+fRTy6WJfWhdrg7BzT+lkvFdl2egOPkFBQgxd88mKeCly6F4nPDg64G1AyY01dfyR9Ekbe5a41nuNinxpTyTdlTl4/CHrsD4EkYtwyg6M3dsBZhlj794an9dHqEtyfAv/DYsNXqdzv8Pqgqi46LfVp+EDwIo=
  bucket: olamothe
  local-dir: bin
  upload-dir: searchui/v$PACKAGE_JSON_VERSION
  acl: public_read
  skip_cleanup: true
  on:
    repo: coveo/search-ui
    all_branches: true
branches:
  only:
  - JSUI-1923
