sudo: required
language: node_js
addons:
  chrome: stable
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: kEnVWejWIDAo6bWMovYAd/oHXJPOtfAdUg/I0tQu8a4BWBo6SaO05fLs/7DjRkXS2vAA++0aim96lQl0TmMFqpooYCf0XTO/797FPVQx0yA3W5XI20vwWUGxW4jKy56WQBTvxPzdSsSlOMcoVVYU8ID86D7coiAuzdfw8olaqmlN3gzcSwvrWbJsa3tAzQFTC0vvWgFyURxB79amYkl5y+KDQW4i7iSDTicXHj/5Tm6RxX3hUUYZFe/p/XenU3/KF3046EL3aYv98QpA3S8FXxMR5lrbLqXHCF8zMljzR2fVmlPSsrLgsXbZY9bvk64wgD+3borN42kab0kQxH6fPoCi7bKtQOoOdq1Z7b+YGRIUzEazl0goM7sQTq9aa3rR2+gzyYe4aLuCo3A9vOFIUGqEEiwmy2SCN7wa/yiWjreaaziRuZPaVo14cGfjtQ1z8S2okYFVmJM8EHzestpsnwTSDApX1w5cBlpYfFToGPYBR6B/Lhn1h6miUd+xNL+KJQpOXPOJVeiNacFzLG1nCq8wGwQ/terW5sODdkPLuKUV6UF6ZR10WED2WlqmdrtnDg5+t+3WMxX5oQGdwq+Zv5rlJVboa0WgDLhsEfNrycK9ncWu2tGE2MUsnEiwqqbqfh/O7E+xBbGAqk/rXLfCcWrSz+6o3K6/Xaq/NA6gAhQ=
    on_success: never
    on_failure: always
    on_pull_requests: false
node_js:
- 12.18.3
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - npm install -g npm@6.14.7
  - sudo apt-get install libgconf2-4
  - export SOURCE_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - export IS_FORKED_PULL_REQUEST=$([[ $TRAVIS_PULL_REQUEST != false && $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]] && echo true || echo false)
  - export HAS_BETA_TAG=$([[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+-beta$ && $IS_FORKED_PULL_REQUEST = false ]] && echo true || echo false)
  - export HAS_RELEASE_TAG=$([[ $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ && $IS_FORKED_PULL_REQUEST = false ]] && echo true || echo false)
  - export IS_ON_FEATURE_BRANCH=$([[ $SOURCE_BRANCH =~ ^JSUI-[0-9]+ && $IS_FORKED_PULL_REQUEST = false ]] && echo true || echo false)
  - export IS_NIGHTLY=$([[ $HAS_BETA_TAG = true && $TRAVIS_EVENT_TYPE = cron ]] && echo true || echo false)
  - "echo 'SOURCE_BRANCH: $SOURCE_BRANCH'"
  - "echo 'IS_FORKED_PULL_REQUEST: $IS_FORKED_PULL_REQUEST'"
  - "echo 'HAS_BETA_TAG: $HAS_BETA_TAG'"
  - "echo 'HAS_RELEASE_TAG: $HAS_RELEASE_TAG'"
  - "echo 'IS_ON_FEATURE_BRANCH: $IS_ON_FEATURE_BRANCH'"
  - "echo 'IS_NIGHTLY: $IS_NIGHTLY'"
script:
- source read.version.sh
- echo $PACKAGE_JSON_VERSION
- yarn run injectTag
- yarn run build
- if [ "x$TRAVIS_TAG" != "x" ]; then yarn run minimize ; fi
- yarn run unitTests
- if [ "x$TRAVIS_TAG" != "x" ]; then yarn run accessibilityTests ; fi
- set +e
- yarn run uploadCoverage
- set -e
- yarn run validateTypeDefinitions
after_success:
- if [ "x$TRAVIS_TAG" != "x" ]; then bash ./deploy.doc.sh ; fi
- yarn run docsitemap
- yarn run zipForGitReleases
env:
  global:
  - COMMIT_AUTHOR_EMAIL: sandbox_JSUI@coveo.com
deploy:
  - provider: npm
    email: sandbox_JSUI@coveo.com
    skip_cleanup: true
    api_key:
      secure: g6Uxgz8nKnR7CVu58JSv4wi7hhRUzV4C2znda2Yq/dTxjjKTBJk6HVnXOlpcN2vVXD7Tc/HGnjLVABEzpfeEfiZXc1tEzalS+EfHXcTjGOzr84IiG4ZRlurayI5K2MIV6s/sLN/up2vOGhE0e9Clx+ot7mlJXgiMZ0+IREcD2IWhC+VfpVkt8Owhf8J33+wRvYYKdHpkaRXbcJS6563nDIOHSzLEXd0EFXQTODdBoRTdPfTnl3kgHmFw0so6gvONbG70dV4TrPdiqr58iJjCta9Cz2Nae+AMJPjzS2zTtS9DjiRrQxls7IHoAvKWWTbRzpbdgpMpvApjRoqdHiBEQk1Wv49zfeIBk4at9UQwH8v8vU139PaZga90/UAOdK/rRPxO0ptlYqE9MTnN4Uze1i7eFiiqyEo8pTDDFxv03672tYFIiBxHoyMuAHxcEfkgGbJYRazkAurjzqGKv7Kj2BCFCDQgut/akgsKZZiJygmQnQoDFRVkLhv2worm03WgTh7cE5efgVTu/I0jJTHmo3fAVB47lpdzxSmXYLKsFllukUN/7/P5HiIUKeb9Lr0tp7N2DbxKkLHyGxKv1YXyffPebmiV+D5xeDBRvm/AB9qR4rJc9dP5wXOqnkhayn9chJvCWrJ46unX3yotuQcd7iQENhHhThhclLwq8E9odVY=
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "$HAS_RELEASE_TAG == true"
  - provider: script
    script: node deploy.beta.js
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "$HAS_BETA_TAG == true"
  - provider: releases
    api_key:
      secure: jKNS2mWnLUP5kQkjApoIFxQVXAr8ed3nsTIltY6gOvf1/2kbkS0WbzR7Km9lewFA2ZEBSFAu/ek+ewXjEx8FVQAe3CeCS1sS5RVqU/2YvFGBPYzzVw1l3FOJkQsvruRc7UzkznXbLvk+7LerHDpsy3p6ut8stMokztiq8QyWN+GHhrB/QgBQV/swPx40QknAIXndtLEPQfttukLowAdH9ml2BgrgE0/3iitmja/8eIQxVT6dlFyXYV+iU44kPyS595wM7eakUGXNFB2W9sUZ9IY/8lUqPz85G3FkKyiPv3SZJRs158/32+vvdXAtT/wtHjP5PqESPv/pL31M9IpQYYIdTSPwUZtOdRZ6JrxV/xusQ2Nm5p3qNrKgtkEZ921BGHJEMK9xs0yAhMuT39JLhoZE30g8SXokWQWi6WzrRELODYubVMaXTmfgv2ZZN4T3B8xNSabmE3Jm7Gj5Lb9wdR+pbWxPlB475i4H7grOHAN9xRIWokAIIN9RuTPRx1XuxhLUI9BH/GrJXNZbv1800rqF15W9Yuw1RqMfrSWq2snyDalXW3gLHYeAFAP1hfD2mU1zySjP/HQ6VkCwmgCjlAg4W5xK4NlXX0C/EIkoLKhSefxLdhquMZQTION+v0fOvl7Kdz17vt231dEIjNZxsBlLL+JZoxOZA5tVRDMNbko=
    file_glob: true
    file:
    - search-ui.zip
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "$HAS_RELEASE_TAG == true || $HAS_BETA_TAG == true"
  - provider: s3
    access_key_id: AKIAYKDJLZIT462WODCI
    secret_access_key:
      secure: sT8isIiaAIg/Ic7x8cCD3anwCEHAyzG/IWkngmkf5c128NEwUIUdmsQJ1hi4Bw84zk1OOb3id+yXjeaTuKDgIkxe/jk3e2xZ7xElfLNTOln6QLkgsYpKFtGHiKjROOHOb5+Es6L1mxpHWbXH9ebmEhRduUw/BeHWW2MfZmfb434DgvatViRm8DOeROeqlYnbCda5ZELuT5SdwEs/CbExaiSL0WKVoTvcxbe+At4uVnTuc6SYyOvRoblx/q6Ra6mdRipluMs7Go93eu/Oqo7cZ2akrNSi/WBXGqL/wXxe2pYsziSABWjQaqWXD/jKte1ZBx7OXssn88DUKat/RrL7Ak30WHzgY/goiNV+EPT/wtNYWHP3suAzzGqNNMhsPx0lSI7vSUga72J3hV1TOsX9ORosiRm1c2fnmNB9vJdH7yAX7lWpqH2XuOrldVvvTGazSJYx93eBukDViFCZ6egeb+gMT8VQ38uitwd9BZaMhycoujZgSjhx7JnbHUoUdXkdT3XBNV7fINTozWCNJW81iJN+JuLZzneJ/CbjmjkfGcVoFFPCD9rGSj8DbgvWpt8rkwI4ZfHTNOgO9iWgSklpk9r2wgM7Z87V2Zpu8UX/QCFxy8IREtJUo6X9YG9nBoy21wUa9zia2SWpideur9cXb6U0+q84onHVlA0Ehp/1OYs=
    bucket: coveo-nprod-binaries
    local-dir: bin
    upload-dir: proda/StaticCDN/searchui/v$PACKAGE_JSON_VERSION
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "$HAS_RELEASE_TAG == true"
  - provider: s3
    access_key_id: AKIAYKDJLZIT462WODCI
    secret_access_key:
      secure: sT8isIiaAIg/Ic7x8cCD3anwCEHAyzG/IWkngmkf5c128NEwUIUdmsQJ1hi4Bw84zk1OOb3id+yXjeaTuKDgIkxe/jk3e2xZ7xElfLNTOln6QLkgsYpKFtGHiKjROOHOb5+Es6L1mxpHWbXH9ebmEhRduUw/BeHWW2MfZmfb434DgvatViRm8DOeROeqlYnbCda5ZELuT5SdwEs/CbExaiSL0WKVoTvcxbe+At4uVnTuc6SYyOvRoblx/q6Ra6mdRipluMs7Go93eu/Oqo7cZ2akrNSi/WBXGqL/wXxe2pYsziSABWjQaqWXD/jKte1ZBx7OXssn88DUKat/RrL7Ak30WHzgY/goiNV+EPT/wtNYWHP3suAzzGqNNMhsPx0lSI7vSUga72J3hV1TOsX9ORosiRm1c2fnmNB9vJdH7yAX7lWpqH2XuOrldVvvTGazSJYx93eBukDViFCZ6egeb+gMT8VQ38uitwd9BZaMhycoujZgSjhx7JnbHUoUdXkdT3XBNV7fINTozWCNJW81iJN+JuLZzneJ/CbjmjkfGcVoFFPCD9rGSj8DbgvWpt8rkwI4ZfHTNOgO9iWgSklpk9r2wgM7Z87V2Zpu8UX/QCFxy8IREtJUo6X9YG9nBoy21wUa9zia2SWpideur9cXb6U0+q84onHVlA0Ehp/1OYs=
    bucket: coveo-nprod-binaries
    local-dir: bin
    upload-dir: proda/StaticCDN/searchui/v$PACKAGE_JSON_VERSION/$PACKAGE_PATCH_VERSION
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "$HAS_RELEASE_TAG == true"
  - provider: s3
    access_key_id: AKIAQ6FOLK5RDONGHVBY
    secret_access_key:
      secure: XL74wJ5088h082Ev6ZwPdEInliIF7/Dqvqz4rJYaXS3CU/KpsoeDhtV4wnF7Dr6P61AF6x8B4Q4uJKnOYBpg7oBjY7efsCDTJo2FeGxqM7j58Trdmh+kfDLmo9Rt06mTyvhKA/DC9tb7/Didnqs4/zDW0NUTqWu5ggnu0GO54kqoZon776ZCVrLzvSPpDh1VLqNTK5Z2ozIlO3XJc3y+QZeeG/yJBb3RcOnhv91+EIHib5y+HU5SoBIq71m2dbrR3q+V80mX+b9RAJDyb6wRjF8lDnrybaMF6Vf+FfzDj3fu1Z+juro8LN8afwMwKCZ4t8UHEB5n5/eD3oD6NwIkOQEPWMshbJr3UdM524dFrtcKQ5F7nvY8ZCE1a6zMGofmzINOb+qpiR5hlvIP375TaTVt7wIe7MM1CIuBferIqjL9fPmaMqcNRAxDt1HpI9HKOJ5ETSVXEpxviaBqYJjACwXgaXU4+5GsmcSprBSaBuBGJTVWQ5N7ewsxRP/2c3XmtMkB9lc+exwpF8/FvsJ6RbzNi1RhbA78r67XJcuK/2xD4aVYByd6PETVM1I7Bq0+LrECeEDqsTMcGHfAwc6ir69Lw0t/KVG/yHwbWyfwiYbkajfcQWYU669rD6ikY1B87assrqPDXneu65FxmoCYDMwBGRp8/w2gS7HSZmom5zA=
    bucket: coveo-ndev-binaries
    local-dir: bin
    upload-dir: proda/StaticCDN/searchui/nightly
    skip_cleanup: true
    on:
      tags: true
      repo: coveo/search-ui
      all_branches: true
      condition: "$IS_NIGHTLY == true"
  - provider: s3
    access_key_id: AKIAQ6FOLK5RDONGHVBY
    secret_access_key:
      secure: XL74wJ5088h082Ev6ZwPdEInliIF7/Dqvqz4rJYaXS3CU/KpsoeDhtV4wnF7Dr6P61AF6x8B4Q4uJKnOYBpg7oBjY7efsCDTJo2FeGxqM7j58Trdmh+kfDLmo9Rt06mTyvhKA/DC9tb7/Didnqs4/zDW0NUTqWu5ggnu0GO54kqoZon776ZCVrLzvSPpDh1VLqNTK5Z2ozIlO3XJc3y+QZeeG/yJBb3RcOnhv91+EIHib5y+HU5SoBIq71m2dbrR3q+V80mX+b9RAJDyb6wRjF8lDnrybaMF6Vf+FfzDj3fu1Z+juro8LN8afwMwKCZ4t8UHEB5n5/eD3oD6NwIkOQEPWMshbJr3UdM524dFrtcKQ5F7nvY8ZCE1a6zMGofmzINOb+qpiR5hlvIP375TaTVt7wIe7MM1CIuBferIqjL9fPmaMqcNRAxDt1HpI9HKOJ5ETSVXEpxviaBqYJjACwXgaXU4+5GsmcSprBSaBuBGJTVWQ5N7ewsxRP/2c3XmtMkB9lc+exwpF8/FvsJ6RbzNi1RhbA78r67XJcuK/2xD4aVYByd6PETVM1I7Bq0+LrECeEDqsTMcGHfAwc6ir69Lw0t/KVG/yHwbWyfwiYbkajfcQWYU669rD6ikY1B87assrqPDXneu65FxmoCYDMwBGRp8/w2gS7HSZmom5zA=
    bucket: coveo-ndev-binaries
    local-dir: bin
    upload-dir: proda/StaticCDN/searchui/pr/$TRAVIS_BRANCH
    skip_cleanup: true
    on:
      repo: coveo/search-ui
      all_branches: true
      condition: "$IS_ON_FEATURE_BRANCH == true"

after_deploy:
- node invalidate.cloudfront.js
branches:
  only:
  - master
  - "/^.*release.*$/"
  - "/2\\.[0-9]+\\.[0-9]+/"
