sudo: false
language: node_js
notifications:
  email:
    on_success: change
    on_failure: always
node_js:
- 8.5.0
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - npm install -g npm@5.5.1
script:
- source read.version.sh
- echo $PACKAGE_JSON_VERSION
- yarn run injectTag
- yarn run build
env:
  global:
  - COMMIT_AUTHOR_EMAIL: sandbox_JSUI@coveo.com
deploy:
  - provider: s3
    access_key_id: AKIAI46KIW3CIP73TTEQ
    secret_access_key:
      secure: M8GpSFcPoyQj8kTA9ptXjTb6wsKUQuI9lpVC0Mph1gbedfle5tNwInJzpUgQhKhrSYZTgtQcDKM9/sYhji6wEp7DGu2NunBzGrotQUe/CNvhhBKNCqVRdGcIFJN971r/jbUvGfYfRCWFD6hCVJnmA438d1kbkRF6yn8r+pti9G4nmgsovM4Xwl6DeeothaeO37yA0hN+Eo+RAnT3K+Ph7CiEt/4PnXQ8F0UI9mvRP5VHnTIDcaIbHpumqR46UK3qqZpvHFiqx2uKdXPz07X7kpP2n/NaXMDslzPktmGK/Zz5jESovVBOXvLSfhJnE/QsUMgONVBAMAL6q+ZkYscrDK4sA5vWtr5BvAPd27RC5UAoTLX30TFknGBcw/ns9nSAvsXQkz/oLdsT21EbfTEVvZMlLjB06FIyXvWyWlP6828fIdluN+CMYr1Uak+Kec0tbhb8lMpUGyY2/X820QSq9a9Q/mTpxgtGSERFOwj/K6N6vLPfwuQEAjv5ISvkjYhivtTH9m3379/qJ+Ki8TNET5Iio6TahYmB9t10CgGDcfaskAI/LoFpkX8c7zKmHrYlNn1Cm7DNc8+/6T0YHdChejvUHSDqJav9qljK9iGplDyICgjmfrQAgN6WXKCqWmyAjjcN+73JAyU3crKJzMr31cg4nvY+ctK4PhTPlN5HNhs=
    bucket: olamothe
    local-dir: bin
    upload-dir: searchui/v$PACKAGE_JSON_VERSION
    acl: public_read
    skip_cleanup: true
    on:
      repo: coveo/search-ui
      all_branches: true
branches:
  only:
  - JSUI-1923