name: Bug Report
description: File a bug report for the ui-kit
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: version
    attributes:
      label: ui-kit version
      description: Which UI-kit version are you using?
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: bug description
      description: Please give a clear description of the bug
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please give a clear description of the steps required to reproduce this bug
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
