name: 'End-to-end certifier'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment in which to run the job
        default: dev
      region:
        description: The region in which to run the job
        default: us-east-1
      package:
        description: The package name
      job:
        description: The name of the job (as defined in the deployment config)
      extra:
        description: Extra parameters passed from the deployment config
        default: '{"JSUI_VERSION":""}'

jobs:
  e2e-certifier:
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy JSUI beta version on Netlify
        run: curl --request POST https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install test dependencies
        working-directory: ${{ github.workspace }}/playwright
        run: npm install && npx playwright install --with-deps

      - name: Validate JSUI version
        working-directory: ${{ github.workspace }}/playwright
        env:
          JSUI_VERSION: ${{ inputs.JSUI_VERSION }}
        run: npm run validate-jsui-version

      - name: Run tests
        working-directory: ${{ github.workspace }}/playwright
        run: npm test
