name: 'End-to-end certifier'

permissions:
  actions: read
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment in which to run the job
        default: dev
      region:
        description: The region in which to run the job
        default: us-east-1
      package:
        description: The package name
      job:
        description: The name of the job (as defined in the deployment config)
      extra:
        description: Extra parameters passed from the deployment config
        default: '{"JSUI_VERSION":""}'
  workflow_call:

jobs:
  e2e-certifier:
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy JSUI beta version on Netlify
        # Only run this step if a JSUI_VERSION has been specified:
        if: ${{ github.event_name == 'workflow_dispatch' && fromJSON(inputs.extra).JSUI_VERSION != '' }}
        run: curl --request POST https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK_ID }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install test dependencies
        working-directory: ${{ github.workspace }}/playwright
        run: npm install && npx playwright install --with-deps

      - name: Validate JSUI version
        # Only run this step if a JSUI_VERSION has been specified:
        if: ${{ github.event_name == 'workflow_dispatch' && fromJSON(inputs.extra).JSUI_VERSION != '' }}
        working-directory: ${{ github.workspace }}/playwright
        env:
          JSUI_VERSION: ${{ fromJSON(inputs.extra || '{"JSUI_VERSION":""}').JSUI_VERSION }}
        run: npm run validate-jsui-version

      - name: Run tests
        working-directory: ${{ github.workspace }}/playwright
        run: npm test

      - uses: actions/upload-artifact@v4
        if: failure() || success()
        with:
          name: playwright-report-html
          path: playwright/playwright-report/
          retention-days: 3
      - uses: actions/upload-artifact@v4
        if: failure() || success()
        with:
          name: playwright-report-json
          path: playwright/test-results.json
          retention-days: 30

  publish-dashboard:
    name: Create playwright-dashboard page
    if: (success() || failure()) && github.event_name == 'schedule' && github.ref == 'refs/heads/master'
    needs: [e2e-certifier]
    runs-on:
      [
        "coveo uid=${{ github.run_id }}-${{ github.run_attempt }}",
        linux,
        arm64,
        ec2,
      ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Publish google chart
        uses: coveo-platform/actions/playwright-dashboard@playwright-dashboard-v1
        with:
          project_name: "JSUI"
          artifact_name: playwright-report-json
          json_report_name: test-results.json
          filter_report_by_branch: "master"  
          filter_report_by_event_type: "schedule"
          filter_report_by_run_name: "Daily E2E Tests for JSUI"
          days_in_past: "30"

      - name: Upload Playwright report and charts to S3
        run: |                   
          aws s3 cp $GITHUB_WORKSPACE/playwright-report-html \
          s3://playwright-dashboard-bucket/JSUI/JSUI-reports/${{ github.run_id }}/ \
          --recursive || true

          aws s3 cp $GITHUB_WORKSPACE/JSUI_chart.html \
          s3://playwright-dashboard-bucket/JSUI/JSUI_chart.html
